# Generated by Django 4.1.7 on 2023-04-25 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Financials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (2000, 2000),
                            (2001, 2001),
                            (2002, 2002),
                            (2003, 2003),
                            (2004, 2004),
                            (2005, 2005),
                            (2006, 2006),
                            (2007, 2007),
                            (2008, 2008),
                            (2009, 2009),
                            (2010, 2010),
                            (2011, 2011),
                            (2012, 2012),
                            (2013, 2013),
                            (2014, 2014),
                            (2015, 2015),
                            (2016, 2016),
                            (2017, 2017),
                            (2018, 2018),
                            (2019, 2019),
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                        ],
                        help_text="За какой год информация ниже актуальна",
                        verbose_name="Отчет за год",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Показывает общую сумму денег, которую компания заработала за определенный год",
                        max_digits=10,
                        null=True,
                        verbose_name="Общая выручка",
                    ),
                ),
                (
                    "expenses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Поле может включать все расходы, связанные с бизнесом, такие как зарплата сотрудников, аренда помещения, закупка оборудования и т.д.",
                        max_digits=10,
                        null=True,
                        verbose_name="Расходы",
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Это поле показывает разницу между выручкой и себестоимостью товаров или услуг.",
                        max_digits=10,
                        null=True,
                        verbose_name="Валовая прибыль",
                    ),
                ),
                (
                    "net_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Это поле может показывать сумму денег, которую компания заработала после вычета всех расходов.",
                        max_digits=10,
                        null=True,
                        verbose_name="Чистая прибыль",
                    ),
                ),
                (
                    "taxes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Это поле может включать информацию о том, сколько налогов компания заплатила за определенный период времени.",
                        max_digits=10,
                        null=True,
                        verbose_name="Налоги",
                    ),
                ),
                (
                    "dividends",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Это поле может показывать сумму денег, которую компания выплатила своим акционерам",
                        max_digits=10,
                        null=True,
                        verbose_name="Дивиденды",
                    ),
                ),
                (
                    "margin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Это поле показывает процентную прибыль компании, которая остается после вычета всех расходов от общей выручки.",
                        max_digits=10,
                        null=True,
                        verbose_name="Маржа",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enterprises.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
