# Generated by Django 4.1.7 on 2023-05-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprises", "0002_financials"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Электроника, одежда, услуги и т.д.",
                        max_length=255,
                        verbose_name="Категория продукта",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Описание категории продукта"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Categories",
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Фрукты, овощи, брюки и т. д.",
                        max_length=255,
                        verbose_name="Тип продукта",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание типа продукта"),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        help_text="Категория продукта",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="products.productcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название продукта"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание продукта"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="product_images", verbose_name="Изображение продукта"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="enterprises.company",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.producttype",
                        verbose_name="Тип продукта",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
